cmake_minimum_required(VERSION 3.20)
if(NOT IS_DIRECTORY "${MODULE_DIRECTORY}")
  message(FATAL_ERROR "Set MODULE_DIRECTORY to the directory containing collected module binaries")
endif()
get_filename_component(MODULE_DIRECTORY "${MODULE_DIRECTORY}" ABSOLUTE)
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../game/tce_version.h" version_line REGEX "^#define TCE_VERSION ")
string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" version "${version_line}")
if(NOT version)
  message(FATAL_ERROR "Invalid TCE_VERSION")
endif()
set(package_name "tce2-${version}.pk3")
file(GLOB installed_packages "${MODULE_DIRECTORY}/*.pk3")
foreach(installed IN LISTS installed_packages)
  get_filename_component(installed_name "${installed}" NAME)
  if(NOT installed_name STREQUAL package_name)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${installed}"
      OUTPUT_VARIABLE entries COMMAND_ERROR_IS_FATAL ANY)
    if(entries MATCHES "(^|\n)(cgame|ui)[^/\r\n]*[.](dll|so)(\r?\n|$)")
      message(FATAL_ERROR "Conflicting client binary package: ${installed}. Move it outside the mod search path before packaging.")
    endif()
  endif()
endforeach()
get_filename_component(stage "${MODULE_DIRECTORY}/../build/tce2-client-package-${version}" ABSOLUTE)
file(MAKE_DIRECTORY "${stage}/tce2/${version}")
set(module_files)
foreach(module cgame ui)
  foreach(suffix _mp_x86.dll _mp_x64.dll .mp.i386.so .mp.x86_64.so)
    if(EXISTS "${MODULE_DIRECTORY}/${module}${suffix}")
      list(APPEND module_files "${module}${suffix}")
      file(COPY "${MODULE_DIRECTORY}/${module}${suffix}" DESTINATION "${stage}")
    else()
      message(FATAL_ERROR "Missing client binary ${module}${suffix}; collect all four builds first")
    endif()
  endforeach()
endforeach()
if(NOT module_files)
  message(FATAL_ERROR "No supported native module binaries found")
endif()
file(WRITE "${stage}/tce2/${version}/client.manifest" "${version}")
list(APPEND module_files "tce2/${version}/client.manifest")
# Required CQB-style compass marker resources; reference pak files stay untouched.
foreach(asset radar_arrow.tga radar_dot.tga)
  file(MAKE_DIRECTORY "${stage}/gfx/misc")
  file(COPY "${CMAKE_CURRENT_LIST_DIR}/../assets/gfx/misc/${asset}" DESTINATION "${stage}/gfx/misc")
  list(APPEND module_files "gfx/misc/${asset}")
endforeach()

execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${MODULE_DIRECTORY}/${package_name}" --format=zip -- ${module_files}
  WORKING_DIRECTORY "${stage}" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Packaged client modules and manifest into ${MODULE_DIRECTORY}/${package_name}; qagame remains loose")
