# Share SDK test objects only for identical source sets and compilation contexts.
# Production modules remain untouched. Test files and linker options stay per-test.
option(TCE_REUSE_TEST_OBJECTS "Reuse identical SDK objects across original-comparison tests" ON)
if(BUILD_TESTING AND TCE_REUSE_TEST_OBJECTS)
  get_property(tce_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  set(tce_saved 0)
  set(tce_shared 0)
  set(tce_report "target,object_library,source_count\n")
  foreach(tce_target IN LISTS tce_targets)
    get_target_property(tce_kind ${tce_target} TYPE)
    if(NOT tce_kind STREQUAL "EXECUTABLE" OR NOT tce_target MATCHES "^tce_.*_test$")
      continue()
    endif()
    get_target_property(tce_all ${tce_target} SOURCES)
    set(tce_body ${tce_all})
    list(FILTER tce_body EXCLUDE REGEX "(^|/)tests/")
    list(FILTER tce_body INCLUDE REGEX "[.]c$")
    list(LENGTH tce_body tce_count)
    if(tce_count LESS 20)
      continue()
    endif()
    # Preserve exact compiler property order; never combine UIDLL/CGAMEDLL/GAMEDLL.
    set(tce_props COMPILE_DEFINITIONS COMPILE_OPTIONS COMPILE_FLAGS INCLUDE_DIRECTORIES
      COMPILE_FEATURES C_STANDARD C_STANDARD_REQUIRED C_EXTENSIONS MSVC_RUNTIME_LIBRARY
      INTERPROCEDURAL_OPTIMIZATION POSITION_INDEPENDENT_CODE)
    set(tce_context "")
    foreach(tce_prop IN LISTS tce_props)
      get_target_property(tce_value ${tce_target} ${tce_prop})
      string(APPEND tce_context "|${tce_prop}=${tce_value}")
    endforeach()
    # This repository's eligible targets link system winmm only. Decline usage
    # requirements from new CMake targets rather than silently dropping them.
    get_target_property(tce_links ${tce_target} LINK_LIBRARIES)
    if(tce_links AND NOT tce_links STREQUAL "winmm")
      continue()
    endif()
    get_target_property(tce_pch ${tce_target} PRECOMPILE_HEADERS)
    if(tce_pch)
      continue()
    endif()
    list(SORT tce_body)
    string(SHA256 tce_key "${tce_body}|${tce_context}")
    string(SUBSTRING "${tce_key}" 0 16 tce_key)
    set(tce_obj "tce_test_objects_${tce_key}")
    if(NOT TARGET ${tce_obj})
      add_library(${tce_obj} OBJECT ${tce_body})
      foreach(tce_prop IN LISTS tce_props)
        get_target_property(tce_value ${tce_target} ${tce_prop})
        if(NOT tce_value STREQUAL "tce_value-NOTFOUND")
          set_property(TARGET ${tce_obj} PROPERTY ${tce_prop} "${tce_value}")
        endif()
      endforeach()
      math(EXPR tce_shared "${tce_shared}+1")
    else()
      math(EXPR tce_saved "${tce_saved}+${tce_count}")
    endif()
    list(REMOVE_ITEM tce_all ${tce_body})
    set_property(TARGET ${tce_target} PROPERTY SOURCES "${tce_all}")
    target_sources(${tce_target} PRIVATE $<TARGET_OBJECTS:${tce_obj}>)
    string(APPEND tce_report "${tce_target},${tce_obj},${tce_count}\n")
  endforeach()
  file(WRITE "${CMAKE_BINARY_DIR}/test-object-reuse.csv" "${tce_report}")
  message(STATUS "TC test object reuse: ${tce_shared} contexts, ${tce_saved} duplicate C compilations removed")
endif()
