# Source lists from the original Visual Studio SDK projects.

set(qagame_SOURCES
  botai/ai_cmd.c
  botai/ai_dmgoal_mp.c
  botai/ai_dmnet_mp.c
  botai/ai_dmq3.c
  botai/ai_main.c
  botai/ai_script.c
  botai/ai_script_actions.c
  botai/ai_team.c
  game/bg_animation.c
  game/bg_animgroup.c
  game/bg_campaign.c
  game/bg_character.c
  game/bg_classes.c
  game/bg_misc.c
  game/bg_pmove.c
  game/bg_slidemove.c
  game/bg_sscript.c
  game/bg_stats.c
  game/bg_tracemap.c
  game/g_active.c
  game/g_alarm.c
  game/g_antilag.c
  game/g_bot.c
  game/g_buddy_list.c
  game/g_character.c
  game/g_client.c
  game/g_cmds.c
  game/g_cmds_ext.c
  game/g_combat.c
  game/g_config.c
  game/g_fireteams.c
  game/g_items.c
  game/g_main.c
  game/g_match.c
  game/g_mem.c
  game/g_misc.c
  game/g_missile.c
  game/g_mover.c
  game/g_multiview.c
  game/g_props.c
  game/g_referee.c
  game/g_save.c
  game/g_script.c
  game/g_script_actions.c
  game/g_session.c
  game/g_spawn.c
  game/g_stats.c
  game/g_sv_entities.c
  game/g_svcmds.c
  game/g_syscalls.c
  game/g_systemmsg.c
  game/g_target.c
  game/g_team.c
  game/g_teammapdata.c
  game/g_trigger.c
  game/g_utils.c
  game/g_vote.c
  game/g_weapon.c
  game/q_math.c
  game/q_shared.c
)

set(cgame_SOURCES
  game/bg_animation.c
  game/bg_animgroup.c
  game/bg_campaign.c
  game/bg_character.c
  game/bg_classes.c
  game/bg_misc.c
  game/bg_pmove.c
  game/bg_slidemove.c
  game/bg_sscript.c
  game/bg_stats.c
  game/bg_tracemap.c
  cgame/cg_atmospheric.c
  cgame/cg_character.c
  cgame/cg_commandmap.c
  cgame/cg_consolecmds.c
  cgame/cg_debriefing.c
  cgame/cg_draw.c
  cgame/cg_drawtools.c
  cgame/cg_effects.c
  cgame/cg_ents.c
  cgame/cg_event.c
  cgame/cg_fireteamoverlay.c
  cgame/cg_fireteams.c
  cgame/cg_flamethrower.c
  cgame/cg_info.c
  cgame/cg_limbopanel.c
  cgame/cg_loadpanel.c
  cgame/cg_localents.c
  cgame/cg_main.c
  cgame/cg_marks.c
  cgame/cg_missionbriefing.c
  cgame/cg_multiview.c
  cgame/cg_newDraw.c
  cgame/cg_particles.c
  cgame/cg_players.c
  cgame/cg_playerstate.c
  cgame/cg_polybus.c
  cgame/cg_popupmessages.c
  cgame/cg_predict.c
  cgame/cg_scoreboard.c
  cgame/cg_servercmds.c
  cgame/cg_snapshot.c
  cgame/cg_sound.c
  cgame/cg_spawn.c
  cgame/cg_statsranksmedals.c
  cgame/cg_syscalls.c
  cgame/cg_trails.c
  cgame/cg_view.c
  cgame/cg_weapons.c
  cgame/cg_window.c
  game/q_math.c
  game/q_shared.c
  ui/ui_shared.c
)

set(ui_SOURCES
  game/bg_campaign.c
  game/bg_classes.c
  game/bg_misc.c
  game/q_math.c
  game/q_shared.c
  ui/ui_atoms.c
  ui/ui_gameinfo.c
  ui/ui_loadpanel.c
  ui/ui_main.c
  ui/ui_players.c
  ui/ui_shared.c
  ui/ui_syscalls.c
  ui/ui_util.c
)
